name: Samples End to End Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: End to End Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Get autokitteh
        run: curl -sSL https://get.autokitteh.sh | bash
      - name: Test
        run: go test -v ./tests
